-- ============================================================
-- FILE 05 : Business Playbook — Executive KPIs
-- ============================================================
-- Dataset : bigquery-public-data.ga4_obfuscated_sample_ecommerce
-- Goal    : Combine acquisition, conversion, and retention signals
--           into actionable executive KPIs for an e-commerce business
--           — the kind of summary prepared for a weekly growth review.
--
-- 💡 How to run: copy the full query into BigQuery and click Run.
-- ============================================================


-- ============================================================
-- Q1 — Weekly acquisition & conversion summary
--
-- Business question: what does our growth look like week over week?
-- This is the top-level view in a weekly e-commerce growth review.
-- ============================================================

WITH weekly_metrics AS (
  SELECT
    DATE_TRUNC(PARSE_DATE('%Y%m%d', event_date), WEEK(MONDAY)) AS week,
    COUNT(DISTINCT CASE WHEN event_name = 'session_start'
      THEN user_pseudo_id END)                                  AS new_sessions,
    COUNT(DISTINCT CASE WHEN event_name = 'first_visit'
      THEN user_pseudo_id END)                                  AS new_users,
    COUNT(DISTINCT CASE WHEN event_name = 'purchase'
      THEN user_pseudo_id END)                                  AS converting_users,
    ROUND(SUM(ecommerce.purchase_revenue), 2)                   AS revenue
  FROM `bigquery-public-data.ga4_obfuscated_sample_ecommerce.events_*`
  WHERE _TABLE_SUFFIX BETWEEN '20201101' AND '20210131'
  GROUP BY week
)

SELECT
  week,
  new_sessions,
  new_users,
  converting_users,
  revenue,
  ROUND(SAFE_DIVIDE(converting_users, new_users) * 100, 2)            AS user_cvr_pct,
  ROUND(SAFE_DIVIDE(revenue, converting_users), 2)                    AS avg_revenue_per_converter,

  -- Week-over-week growth signals
  LAG(new_users)   OVER (ORDER BY week)                               AS prev_week_users,
  ROUND(SAFE_DIVIDE(new_users - LAG(new_users) OVER (ORDER BY week),
    LAG(new_users) OVER (ORDER BY week)) * 100, 1)                    AS user_growth_wow_pct,

  LAG(revenue)     OVER (ORDER BY week)                               AS prev_week_revenue,
  ROUND(SAFE_DIVIDE(revenue - LAG(revenue) OVER (ORDER BY week),
    LAG(revenue) OVER (ORDER BY week)) * 100, 1)                      AS revenue_growth_wow_pct

FROM weekly_metrics
ORDER BY week;


-- ============================================================
-- Q2 — User LTV proxy by acquisition channel
--
-- Business question: which channel acquires users with the
-- highest long-term value?
-- Proxy: total revenue generated by a user across all sessions,
-- grouped by their first acquisition channel.
-- ============================================================

WITH user_first_channel AS (
  SELECT
    user_pseudo_id,
    CASE
      WHEN traffic_source.medium = 'organic'                THEN 'Organic Search'
      WHEN traffic_source.medium = 'cpc'                    THEN 'Paid Search'
      WHEN traffic_source.medium IN ('referral','affiliate') THEN 'Referral'
      WHEN traffic_source.source = '(direct)'
        OR traffic_source.medium = '(none)'                 THEN 'Direct'
      ELSE 'Other'
    END AS first_channel
  FROM `bigquery-public-data.ga4_obfuscated_sample_ecommerce.events_*`
  WHERE _TABLE_SUFFIX BETWEEN '20201101' AND '20210131'
    AND event_name = 'first_visit'
  QUALIFY ROW_NUMBER() OVER (PARTITION BY user_pseudo_id ORDER BY event_timestamp) = 1
),

user_revenue AS (
  SELECT
    user_pseudo_id,
    ROUND(SUM(ecommerce.purchase_revenue), 2) AS total_revenue,
    COUNT(DISTINCT PARSE_DATE('%Y%m%d', event_date)) AS active_days,
    COUNTIF(event_name = 'purchase')             AS total_purchases
  FROM `bigquery-public-data.ga4_obfuscated_sample_ecommerce.events_*`
  WHERE _TABLE_SUFFIX BETWEEN '20201101' AND '20210131'
  GROUP BY user_pseudo_id
)

SELECT
  c.first_channel,
  COUNT(DISTINCT c.user_pseudo_id)                        AS total_users,
  COUNT(DISTINCT CASE WHEN r.total_purchases > 0
    THEN c.user_pseudo_id END)                            AS paying_users,
  ROUND(SAFE_DIVIDE(
    COUNT(DISTINCT CASE WHEN r.total_purchases > 0 THEN c.user_pseudo_id END),
    COUNT(DISTINCT c.user_pseudo_id)) * 100, 1)           AS paying_rate_pct,

  -- Average revenue per paying user = LTV proxy
  ROUND(SAFE_DIVIDE(
    SUM(r.total_revenue),
    NULLIF(COUNT(DISTINCT CASE WHEN r.total_purchases > 0 THEN c.user_pseudo_id END), 0)
  ), 2)                                                   AS avg_ltv_proxy,

  ROUND(SUM(r.total_revenue), 2)                          AS channel_total_revenue
FROM user_first_channel c
LEFT JOIN user_revenue r USING (user_pseudo_id)
GROUP BY c.first_channel
ORDER BY channel_total_revenue DESC;


-- ============================================================
-- Q3 — Churn signal: users who engaged but never converted
--
-- Business question: which users are "stuck" in the funnel —
-- engaged enough to add to cart but never completed a purchase?
-- In e-commerce terms: users who showed purchase intent but never completed checkout.
-- These are the highest-value re-engagement targets.
-- ============================================================

WITH user_funnel AS (
  SELECT
    user_pseudo_id,
    COUNTIF(event_name = 'session_start')   AS sessions,
    COUNTIF(event_name = 'view_item')       AS item_views,
    COUNTIF(event_name = 'add_to_cart')     AS cart_adds,
    COUNTIF(event_name = 'begin_checkout')  AS checkouts_started,
    COUNTIF(event_name = 'purchase')        AS purchases,
    MAX(PARSE_DATE('%Y%m%d', event_date))   AS last_seen_date
  FROM `bigquery-public-data.ga4_obfuscated_sample_ecommerce.events_*`
  WHERE _TABLE_SUFFIX BETWEEN '20201101' AND '20210131'
  GROUP BY user_pseudo_id
)

SELECT
  -- Funnel stage where the user stopped
  CASE
    WHEN purchases > 0             THEN '5 — Converted'
    WHEN checkouts_started > 0     THEN '4 — Dropped at checkout'
    WHEN cart_adds > 0             THEN '3 — Dropped after cart'
    WHEN item_views > 0            THEN '2 — Dropped after browse'
    ELSE                                '1 — Bounced'
  END                                                    AS funnel_stage,

  COUNT(*)                                               AS user_count,
  ROUND(COUNT(*) / SUM(COUNT(*)) OVER () * 100, 1)       AS share_pct,

  -- Days since last activity — recency signal for re-engagement campaigns
  ROUND(AVG(DATE_DIFF(DATE '2021-02-01', last_seen_date, DAY)), 0) AS avg_days_since_last_visit

FROM user_funnel
GROUP BY funnel_stage
ORDER BY funnel_stage;
